In [1]:
import torch
import torch.nn as nn

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [15]:
class CustomOptim(torch.optim.Optimizer):
    def __init__(self, params, lr=0.001):
        defaults = dict(lr=lr)
        super(CustomOptim, self).__init__(params, defaults)

    def step(self):
        for group in self.param_groups:
            print(f"Group {group}")

class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.fc = nn.Sequential(
            nn.Linear(2, 2),
            nn.ReLU(),
            nn.Linear(2, 1)
        )
        self.b = nn.Parameter(torch.tensor(0.0, device=device), requires_grad=True)

    def forward(self, x):
        return self.fc(x)

In [16]:
model = CustomModel().to(device)
optimizer = CustomOptim(model.parameters())

In [17]:
optimizer.step()

Group {'params': [Parameter containing:
tensor(0., device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.0820,  0.3372],
        [-0.6412,  0.2362]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.5247, -0.1420], device='cuda:0', requires_grad=True), Parameter containing:
tensor([[ 0.2790, -0.3160]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.5028], device='cuda:0', requires_grad=True)], 'lr': 0.001}
